[build]
builder = "dockerfile"
dockerfilePath = "./WebApi/Dockerfile"

[deploy]
startCommand = "dotnet WebApi.dll"
restartPolicyType = "always"
healthcheckPath = "/health"

[[volumes]]
mountPath = "/app/data"

